name: grace
description: A Flutter project with SQLite database integration.
publish_to: 'none'
version: 1.0.6+22

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.14.1
  sqlite3: ^2.4.0
  path_provider: ^2.1.1
  path: ^1.8.3
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

